import Head from "next/head";
import Layout from "@/components/Layout";
import Link from "next/link";
import styles from '../styles/Home.module.css';

const products = [
    { id: 1, name: 'Minimalist Chair', price: 150, description: 'A sleek and modern chair for any room.' },
    { id: 2, name: 'Classic Table', price: 200, description: 'A stylish wooden table.' },
    { id: 3, name: 'Elegant Lamp', price: 80, description: 'A beautiful, adjustable lamp.' },
    { id: 4, name: 'Modern Sofa', price: 600, description: 'A comfortable, contemporary sofa.' },
    { id: 5, name: 'Office Desk', price: 250, description: 'An ergonomic desk for productivity.' },
    { id: 6, name: 'Cozy Armchair', price: 300, description: 'A soft, cozy armchair for relaxation.' },
];

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Layout>
            <div className={styles.container}>
                <h1 className={styles.title}>Welcome to Our Product Store</h1>
                <p className={styles.description}>
                    Explore our products and choose the one that suits your needs.
                </p>

                <div className={styles.productGrid}>
                    {products.map((product) => (
                        <Link key={product.id} href={`/product/${product.id}`}>
                            <div className={styles.card}>
                                <h2>{product.name}</h2>
                                <p>{product.description}</p>
                                <p>Price: ${product.price}</p>
                            </div>
                        </Link>
                    ))}
                </div>
            </div>
        </Layout>    </>
  );
}
